name: mulk
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  quran: ^1.0.6
  bottom_navy_bar: ^6.0.0
  assets_audio_player: ^3.0.3
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: fonts/ScheherazadeNew-Bold.ttf
        - asset: fonts/ScheherazadeNew-Regular.ttf

